<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Android Debug Bridge</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(E)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(D)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(W)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>keyword.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(.)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb.timestamp</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.adb</string>
                </dict>
            </dict>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.adb</string>
    <key>uuid</key>
    <string>95F39BAA-EBD3-468A-9965-2C47C3B30C11</string>
</dict>
</plist>
